[workspace]

members = ["stakedex_sdk", "common", "libs/*", "interfaces/*"]

[workspace.dependencies]
anyhow = "^1.0"
bincode = "^1.0"
borsh = "^0.10"
jupiter-amm-interface = "~0.3.0"
lazy_static = "^1.0"
solana-client = "~1.16"
solana-program = "~1.16"
solana-sdk = "~1.16"
spl-token = "^3.0"
stakedex_deposit_sol_interface = { path = "./interfaces/stakedex_deposit_sol_interface" }
stakedex_deposit_stake_interface = { path = "./interfaces/stakedex_deposit_stake_interface" }
stakedex_eversol_stake_pool = { path = "./libs/eversol_stake_pool" }
stakedex_interface = { path = "./interfaces/stakedex_interface" }
stakedex_lido = { path = "./libs/lido" }
stakedex_marinade = { path = "./libs/marinade" }
stakedex_sdk_common = { path = "./common" }
stakedex_socean_stake_pool = { path = "./libs/socean_stake_pool" }
stakedex_spl_stake_pool = { path = "./libs/spl_stake_pool" }
stakedex_unstake_it = { path = "./libs/unstake_it" }
stakedex_withdraw_stake_interface = { path = "./interfaces/stakedex_withdraw_stake_interface" }
thiserror = "^1.0"
